FROM alpine
WORKDIR /tmp
RUN wget https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_linux_amd64.tar.gz \
    && tar xzf frp_0.37.0_linux_amd64.tar.gz \
	&& cd 0.37.0_linux_amd64 \
	&& mv frps /usr/local/bin \
	&& rm -rf 0.37.0_linux_amd64 \
	&& rm frp_0.37.0_linux_amd64.tar.gz \
	&& mkdir /config \

EXPOSE 7000
VOLUME /config
CMD ["frps", "-c", "/config/frps.ini"]